export const MOSTRAR_PRODUCTOS="MOSTRAR_PRODUCTOS";
export const MOSTRAR_PRODUCTO="MOSTRAR_PRODUCTO";
export const AGREGAR_PRODUCTO="AGREGAR_PRODUCTOS";
export const EDITAR_PRODUCTOS="EDITAR_PRODUCTOS";
export const ELIMINAR_PRODUCTOS="ELIMINAR_PRODUCTOS";
export const ACTION_LOGIN="ACTION_LOGIN";
export const ACTION_LOGOUT="ACTION_LOGOUT";